// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StartPraksisGruppe3Prosjekt.Data;

#nullable disable

namespace StartPraksisGruppe3Prosjekt.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261007102015_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_roles_normalized_name");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("ix_asp_net_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_normalized_user_name");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.ConsentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("changed_by_user_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("Id")
                        .HasName("pk_consent_events");

                    b.HasIndex("PlayerId", "OccurredAt")
                        .HasDatabaseName("ix_consent_events_player_id_occurred_at");

                    b.ToTable("consent_events", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.DatabaseMarker", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset>("MarkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("marked_at");

                    b.HasKey("Id")
                        .HasName("pk_database_marker");

                    b.ToTable("database_marker", null, t =>
                        {
                            t.HasCheckConstraint("ck_database_marker_environment", "environment in ('Development', 'Production')");

                            t.HasCheckConstraint("ck_database_marker_single_row", "id = 1");
                        });
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FeedbackRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("coach_user_id");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_released");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.HasKey("Id")
                        .HasName("pk_feedback_releases");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_feedback_releases_player_id");

                    b.HasIndex("RoundId", "PlayerId", "OccurredAt")
                        .HasDatabaseName("ix_feedback_releases_round_id_player_id_occurred_at");

                    b.ToTable("feedback_releases", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FiveCAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_key");

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_key");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<int?>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_five_c_answers");

                    b.HasIndex("SubmissionId", "QuestionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_five_c_answers_submission_id_question_key");

                    b.ToTable("five_c_answers", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FiveCReflectionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_key");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<string>("Value")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_five_c_reflection_answers");

                    b.HasIndex("SubmissionId", "QuestionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_five_c_reflection_answers_submission_id_question_key");

                    b.ToTable("five_c_reflection_answers", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FiveCSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<string>("QuestionSetVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("question_set_version");

                    b.Property<string>("RespondentRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("respondent_role");

                    b.Property<string>("RespondentUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("respondent_user_id");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_five_c_submissions");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_five_c_submissions_player_id");

                    b.HasIndex("RoundId", "PlayerId", "RespondentUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_five_c_submissions_round_id_player_id_respondent_user_id");

                    b.ToTable("five_c_submissions", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.Guardianship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuardianUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guardian_user_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("Id")
                        .HasName("pk_guardianships");

                    b.HasIndex("GuardianUserId")
                        .HasDatabaseName("ix_guardianships_guardian_user_id");

                    b.HasIndex("PlayerId", "GuardianUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_guardianships_player_id_guardian_user_id");

                    b.ToTable("guardianships", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_players_name");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_players_team_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_players_user_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.PlayerAccessEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int?>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.Property<string>("ViewedByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("viewed_by_role");

                    b.Property<string>("ViewedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("viewed_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_player_access_events");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_player_access_events_round_id");

                    b.HasIndex("PlayerId", "OccurredAt")
                        .HasDatabaseName("ix_player_access_events_player_id_occurred_at");

                    b.HasIndex("ViewedByUserId", "OccurredAt")
                        .HasDatabaseName("ix_player_access_events_viewed_by_user_id_occurred_at");

                    b.ToTable("player_access_events", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.PlayerDeletionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeletedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("Id")
                        .HasName("pk_player_deletion_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_player_deletion_events_occurred_at");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_deletion_events_player_id");

                    b.ToTable("player_deletion_events", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.PlayerPersonalDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea")
                        .HasColumnName("photo");

                    b.Property<string>("PhotoContentType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("photo_content_type");

                    b.Property<string>("PhotoSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("photo_source");

                    b.Property<DateTimeOffset?>("PhotoUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("photo_updated_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_player_personal_details");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_personal_details_player_id");

                    b.ToTable("player_personal_details", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.PlayerSuccessionProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ContractEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("contract_ends_on");

                    b.Property<string>("ContractType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("contract_type");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<string>("TrainingGroup")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("training_group");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_player_succession_profiles");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_succession_profiles_player_id");

                    b.ToTable("player_succession_profiles", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.SuccessionAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AbilityCategory")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ability_category");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("catalog_version");

                    b.Property<DateOnly>("CycleStartsOn")
                        .HasColumnType("date")
                        .HasColumnName("cycle_starts_on");

                    b.Property<bool?>("ExternalNeeded")
                        .HasColumnType("boolean")
                        .HasColumnName("external_needed");

                    b.Property<string>("FirstPosition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("first_position");

                    b.Property<string>("KeyDevelopmentFocus")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("key_development_focus");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<bool?>("PathwayBlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("pathway_blocked");

                    b.Property<int?>("PersonalReadiness")
                        .HasColumnType("integer")
                        .HasColumnName("personal_readiness");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<string>("Projection0To6Months")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("projection0to6months");

                    b.Property<string>("Projection18To36Months")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("projection18to36months");

                    b.Property<string>("Projection6To18Months")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("projection6to18months");

                    b.Property<string>("RatedAs")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rated_as");

                    b.Property<string>("RaterUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("rater_user_id");

                    b.Property<string>("SecondPosition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("second_position");

                    b.Property<string>("SuccessionRisk")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("succession_risk");

                    b.Property<string>("SuperStrengths")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("super_strengths");

                    b.Property<string>("ThirdPosition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("third_position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WhatNow")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("what_now");

                    b.HasKey("Id")
                        .HasName("pk_succession_assessments");

                    b.HasIndex("CycleStartsOn")
                        .HasDatabaseName("ix_succession_assessments_cycle_starts_on");

                    b.HasIndex("PlayerId", "CycleStartsOn", "RaterUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_succession_assessments_player_id_cycle_starts_on_rater_user");

                    b.ToTable("succession_assessments", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.SuccessionRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assessment_id");

                    b.Property<string>("RatingKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rating_key");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_succession_ratings");

                    b.HasIndex("AssessmentId", "RatingKey")
                        .IsUnique()
                        .HasDatabaseName("ix_succession_ratings_assessment_id_rating_key");

                    b.ToTable("succession_ratings", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.SurveyRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("OpensAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opens_at");

                    b.HasKey("Id")
                        .HasName("pk_survey_rounds");

                    b.ToTable("survey_rounds", (string)null);
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.ConsentEvent", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Player", "Player")
                        .WithMany("ConsentEvents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consent_events_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FeedbackRelease", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_releases_players_player_id");

                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.SurveyRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_releases_survey_rounds_round_id");

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FiveCAnswer", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.FiveCSubmission", "Submission")
                        .WithMany("Answers")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_five_c_answers_five_c_submissions_submission_id");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FiveCReflectionAnswer", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.FiveCSubmission", "Submission")
                        .WithMany("Reflection")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_five_c_reflection_answers_five_c_submissions_submission_id");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FiveCSubmission", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_five_c_submissions_players_player_id");

                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.SurveyRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_five_c_submissions_survey_rounds_round_id");

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.Guardianship", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("GuardianUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guardianships_asp_net_users_guardian_user_id");

                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Player", "Player")
                        .WithMany("Guardianships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guardianships_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.Player", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_players_teams_team_id");

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_players_asp_net_users_user_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.PlayerAccessEvent", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_access_events_players_player_id");

                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.SurveyRound", "Round")
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_player_access_events_survey_rounds_round_id");

                    b.Navigation("Player");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.PlayerPersonalDetails", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_personal_details_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.PlayerSuccessionProfile", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_succession_profiles_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.SuccessionAssessment", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_succession_assessments_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.SuccessionRating", b =>
                {
                    b.HasOne("StartPraksisGruppe3Prosjekt.Models.SuccessionAssessment", "Assessment")
                        .WithMany("Ratings")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_succession_ratings_succession_assessments_assessment_id");

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.FiveCSubmission", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Reflection");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.Player", b =>
                {
                    b.Navigation("ConsentEvents");

                    b.Navigation("Guardianships");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.SuccessionAssessment", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("StartPraksisGruppe3Prosjekt.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
